apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: examen-infra
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ndcamachoo/examen-infra-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: MONGO_HOST
          value: mongo
        - name: MONGO_PORT
          value: "27017"
