apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: examen-infra
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ndcamachoo/examen-infra-frontend:latest
          ports:
            - containerPort: 80
