apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: examen-infra
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
